package FileShareApp;


/**
* FileShareApp/fileshareHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fileshare.idl
* Tuesday, May 24, 2022 9:18:48 PM PKT
*/

abstract public class fileshareHelper
{
  private static String  _id = "IDL:FileShareApp/fileshare:1.0";

  public static void insert (org.omg.CORBA.Any a, FileShareApp.fileshare that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FileShareApp.fileshare extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FileShareApp.fileshareHelper.id (), "fileshare");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FileShareApp.fileshare read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_fileshareStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FileShareApp.fileshare value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FileShareApp.fileshare narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileShareApp.fileshare)
      return (FileShareApp.fileshare)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FileShareApp._fileshareStub stub = new FileShareApp._fileshareStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FileShareApp.fileshare unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileShareApp.fileshare)
      return (FileShareApp.fileshare)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FileShareApp._fileshareStub stub = new FileShareApp._fileshareStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
