/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.tutorialspoint.test;

/**
 *
 * @author Asif Ali
 */
import java.util.LinkedHashMap;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "SurveyForm1")
@SessionScoped
public class Survey {

    @ManagedProperty(value = "#{vote}")

    public String selected;

    //getter and setter methods 
    //Generated by Map
    private static Map<String, Object> _5options;

    static {
        _5options = new LinkedHashMap<String, Object>();
        _5options.put("Strongly Agree", "Strongly Agree"); //label, value
        _5options.put("Agree", "Agree");
        _5options.put("Neutral", "Neutral");
        _5options.put("Disagree", "Disagree");
        _5options.put("Strongly Disagree", "Strongly Disagree");

    }

    private static Map<String, Object> _2options;

    static {
        _2options = new LinkedHashMap<String, Object>();
        _2options.put("Yes", "Yes"); //label, value
        _2options.put("No", "No");

    }

    public Map<String, Object> getselectedValue() {
        return _5options;
    }

    public static void setselectedValue(Map<String, Object> fieldValue) {
        Survey._5options = fieldValue;
    }

    public String getSelected() {
        return selected;
    }

    public void setSelected(String selected) {
        this.selected = selected;
    }

    public String q1;

    public void setQ1(String q1) {
        this.q1 = q1;
    }

    public String getQ1() {
        return q1;
    }

    public void setQ1Value(Map<String, Object> fieldValue) {
        this.q1 = q1;
    }

    public Map<String, Object> getQ1Value() {
        return _5options;
    }

    private String q2 = null;

    private String q3 = null;

    private String q4 = null;

    private String q5 = null;

    private String q6 = null;

    private String q7 = null;

    private String q8 = null;

    private String q9 = null;

    private String q10 = null;

    private String q11 = null;

    private String q12 = null;

    private String q13, q14 = null;

    private String q15 = null;

    private String q16 = null;

    private String q17 = null;

    private String q18, q19 = null;

    private String q20 = null;

    private String q21 = null;

    private String q22 = null;

    private String q23 = null;

    private String q24 = null;

    private String q25 = null;

    private String q26 = null;

    private String q27 = null;

    private String com_TeachingApproaches = null;

    private String comfeedbackAsemensts = null;

    private String comRecourseAdminstration = null;

    private String comAdditionalQuestions = null;

    private String comOverallExp = null;

    private String comStdSelfEvaluation = null;

    private String changesRecomending = null;

    private String likeBestAboutInstructor = null;

    private String likeLeastAboutInstructor = null;

    private String furtherConstructiveCom = null;

    public void setQ2(String argq2) {
        q2 = argq2;
    }

    public void setQ3(String argq3) {
        q3 = argq3;
    }

    public void setQ4(String argq4) {
        q4 = argq4;
    }

    public void setQ5(String argq5) {
        q5 = argq5;
    }

    public void setQ6(String argq6) {
        q6 = argq6;
    }

    public void setQ7(String argq7) {
        q7 = argq7;
    }

    public void setQ8(String argq8) {
        q8 = argq8;
    }

    public void setQ9(String argq9) {
        q9 = argq9;
    }

    public void setQ10(String argq10) {
        q10 = argq10;
    }

    public void setQ11(String argq11) {
        q11 = argq11;
    }

    public void setQ12(String argq12) {
        q12 = argq12;
    }

    public void setQ13(String argq13) {
        q13 = argq13;
    }

    public void setQ14(String argq14) {
        q14 = argq14;
    }

    public void setQ15(String argq15) {
        q15 = argq15;
    }

    public void setQ16(String argq16) {
        q16 = argq16;
    }

    public void setQ17(String argq17) {
        q17 = argq17;
    }

    public void setQ18(String argq18) {
        q18 = argq18;
    }

    public void setQ19(String argq19) {
        q18 = argq19;
    }

    public void setQ20(String argq20) {
        q20 = argq20;
    }

    public void setQ21(String argq21) {
        q21 = argq21;
    }

    public void setQ22(String argq22) {
        q22 = argq22;
    }

    public void setQ23(String argq23) {
        q23 = argq23;
    }

    public void setQ24(String argq24) {
        q24 = argq24;
    }

    public void setQ25(String argq25) {
        q25 = argq25;
    }

    public void setQ26(String argq26) {
        q26 = argq26;
    }

    public void setQ27(String argq27) {
        q27 = argq27;
    }

    public void setCom_TeachingApproaches(String argcom_TeachingApproaches) {
        com_TeachingApproaches = argcom_TeachingApproaches;
    }

    public void setComfeedbackAsemensts(String argcomfeedbackAsemensts) {
        comfeedbackAsemensts = argcomfeedbackAsemensts;
    }

    public void setComRecourseAdminstration(String argcomRecourseAdminstration) {
        comRecourseAdminstration = argcomRecourseAdminstration;
    }

    public void setComAdditionalQuestions(String argcomAdditionalQuestions) {
        comAdditionalQuestions = argcomAdditionalQuestions;
    }

    public void setComOverallExp(String argcomOverallExp) {
        comOverallExp = argcomOverallExp;
    }

    public void setComStdSelfEvaluation(String argcomStdSelfEvaluation) {
        comStdSelfEvaluation = argcomStdSelfEvaluation;
    }

    public void setChangesRecomending(String argsChangesRecomending) {
        changesRecomending = argsChangesRecomending;
    }

    public void setLikeBestAboutInstructor(String arglikeBestAboutInstructor) {
        likeBestAboutInstructor = arglikeBestAboutInstructor;
    }

    public void setLikeLeastAboutInstructor(String arglikeLeastAboutInstructor) {
        likeLeastAboutInstructor = arglikeLeastAboutInstructor;
    }

    public void setFurtherConstructiveCom(String argfurtherConstructiveCom) {
        furtherConstructiveCom = argfurtherConstructiveCom;
    }

    public String getQ2() {
        return q2;
    }

    public String getQ3() {
        return q3;
    }

    public String getQ4() {
        return q4;
    }

    public String getQ5() {
        return q5;
    }

    public String getQ6() {
        return q6;
    }

    public String getQ7() {
        return q7;
    }

    public String getQ8() {
        return q8;
    }

    public String getQ9() {
        return q9;
    }

    public String getQ10() {
        return q10;
    }

    public String getQ11() {
        return q11;
    }

    public String getQ12() {
        return q12;
    }

    public String getQ13() {
        return q13;
    }

    public String getQ14() {
        return q14;
    }

    public String getQ15() {
        return q15;
    }

    public String getQ16() {
        return q16;
    }

    public String getQ17() {
        return q17;
    }

    public String getQ18() {
        return q18;
    }

    public String getQ19() {
        return q19;
    }

    public String getQ20() {
        return q20;
    }

    public String getQ21() {
        return q21;
    }

    public String getQ22() {
        return q22;
    }

    public String getQ23() {
        return q23;
    }

    public String getQ24() {
        return q24;
    }

    public String getQ25() {
        return q25;
    }

    public String getQ26() {
        return q26;
    }

    public String getQ27() {
        return q27;
    }

    public String getCom_TeachingApproaches() {
        return com_TeachingApproaches;
    }

    public String getComfeedbackAsemensts() {
        return comfeedbackAsemensts;
    }

    public String getComRecourseAdminstration() {
        return comRecourseAdminstration;
    }

    public String getComAdditionalQuestions() {
        return comAdditionalQuestions;
    }

    public String getComOverallExp() {
        return comOverallExp;
    }

    public String getComStdSelfEvaluation() {
        return comStdSelfEvaluation;
    }

    public String getChangesRecomending() {
        return changesRecomending;
    }

    public String getLikeBestAboutInstructor() {
        return likeBestAboutInstructor;
    }

    public String getLikeLeastAboutInstructor() {
        return likeLeastAboutInstructor;
    }

    public String getFurtherConstructiveCom() {
        return furtherConstructiveCom;
    }

    public static void setQ2Value(Map<String, Object> fieldValue) {
        Survey._5options = fieldValue;
    }

    public static void setQ3Value(Map<String, Object> fieldValue3) {
        Survey._5options = fieldValue3;
    }

    public static void setQ4Value(Map<String, Object> fieldValue4) {
        Survey._5options = fieldValue4;
    }

    public static void setQ5Value(Map<String, Object> fieldValue5) {
        Survey._5options = fieldValue5;
    }

    public static void setQ6Value(Map<String, Object> fieldValue6) {
        Survey._5options = fieldValue6;
    }

    public static void setQ7Value(Map<String, Object> fieldValue7) {
        Survey._5options = fieldValue7;
    }

    public static void setQ8Value(Map<String, Object> fieldValue8) {
        Survey._5options = fieldValue8;
    }

    public static void setQ9Value(Map<String, Object> fieldValue9) {
        Survey._2options = fieldValue9;
    }

    public static void setQ10Value(Map<String, Object> fieldValue10) {
        Survey._2options = fieldValue10;
    }

    public static void setQ11Value(Map<String, Object> fieldValue11) {
        Survey._5options = fieldValue11;
    }

    public static void setQ12Value(Map<String, Object> fieldValue12) {
        Survey._5options = fieldValue12;
    }

    public static void setQ13Value(Map<String, Object> fieldValue13) {
        Survey._5options = fieldValue13;
    }

    public static void setQ14Value(Map<String, Object> fieldValue14) {
        Survey._5options = fieldValue14;
    }

    public static void setQ15Value(Map<String, Object> fieldValue15) {
        Survey._5options = fieldValue15;
    }

    public static void setQ16Value(Map<String, Object> fieldValue16) {
        Survey._5options = fieldValue16;
    }

    public static void setQ17Value(Map<String, Object> fieldValue17) {
        Survey._5options = fieldValue17;
    }

    public static void setQ18Value(Map<String, Object> fieldValue18) {
        Survey._5options = fieldValue18;
    }

    public static void setQ19Value(Map<String, Object> fieldValue19) {
        Survey._5options = fieldValue19;
    }

    public static void setQ20Value(Map<String, Object> fieldValue20) {
        Survey._5options = fieldValue20;
    }

    public static void setQ21Value(Map<String, Object> fieldValue21) {
        Survey._5options = fieldValue21;
    }

    public static void setQ22Value(Map<String, Object> fieldValue22) {
        Survey._2options = fieldValue22;
    }

    public static void setQ23Value(Map<String, Object> fieldValue23) {
        Survey._2options = fieldValue23;
    }

    public static void setQ24Value(Map<String, Object> fieldValue24) {
        Survey._5options = fieldValue24;
    }

    public static void setQ25Value(Map<String, Object> fieldValue25) {
        Survey._5options = fieldValue25;
    }

    public static void setQ26Value(Map<String, Object> fieldValue26) {
        Survey._5options = fieldValue26;
    }

    public static void setQ27Value(Map<String, Object> fieldValue27) {
        Survey._5options = fieldValue27;
    }

    public void setCom_TeachingApproachesValue(String argcom_TeachingApproaches) {
        com_TeachingApproaches = argcom_TeachingApproaches;
    }

    public void setComfeedbackAsemenstsValue(String argcomfeedbackAsemensts) {
        comfeedbackAsemensts = argcomfeedbackAsemensts;
    }

    public void setComRecourseAdminstrationValue(String argcomRecourseAdminstration) {
        comRecourseAdminstration = argcomRecourseAdminstration;
    }

    public void setComAdditionalQuestionsValue(String argcomAdditionalQuestions) {
        comAdditionalQuestions = argcomAdditionalQuestions;
    }

    public void setComOverallExpValue(String argcomOverallExp) {
        comOverallExp = argcomOverallExp;
    }

    public void setComStdSelfEvaluationValue(String argcomStdSelfEvaluation) {
        comStdSelfEvaluation = argcomStdSelfEvaluation;
    }

    public void setChangesRecomendingValue(String argqChangesRecomending) {
        changesRecomending = argqChangesRecomending;
    }

    public void setLikeBestAboutInstructorValue(String arglikeBestAboutInstructor) {
        likeBestAboutInstructor = arglikeBestAboutInstructor;
    }

    public void setLikeLeastAboutInstructorValue(String arglikeLeastAboutInstructor) {
        likeLeastAboutInstructor = arglikeLeastAboutInstructor;
    }

    public void setFurtherConstructiveComValue(String argfurtherConstructiveCom) {
        furtherConstructiveCom = argfurtherConstructiveCom;
    }

    public Map<String, Object> getQ2Value() {
        return _5options;
    }

    public Map<String, Object> getQ3Value() {
        return _5options;
    }

    public Map<String, Object> getQ4Value() {
        return _5options;
    }

    public Map<String, Object> getQ5Value() {
        return _5options;
    }

    public Map<String, Object> getQ6Value() {
        return _5options;
    }

    public Map<String, Object> getQ7Value() {
        return _5options;
    }

    public Map<String, Object> getQ8Value() {
        return _5options;
    }

    public Map<String, Object> getQ9Value() {
        return _2options;
    }

    public Map<String, Object> getQ10Value() {
        return _2options;
    }

    public Map<String, Object> getQ11Value() {
        return _5options;
    }

    public Map<String, Object> getQ12Value() {
        return _5options;
    }

    public Map<String, Object> getQ13Value() {
        return _5options;
    }

    public Map<String, Object> getQ14Value() {
        return _5options;
    }

    public Map<String, Object> getQ15Value() {
        return _5options;
    }

    public Map<String, Object> getQ16Value() {
        return _5options;
    }

    public Map<String, Object> getQ17Value() {
        return _5options;
    }

    public Map<String, Object> getQ18Value() {
        return _5options;
    }

    public Map<String, Object> getQ19Value() {
        return _5options;
    }

    public Map<String, Object> getQ20Value() {
        return _5options;
    }

    public Map<String, Object> getQ21Value() {
        return _5options;
    }

    public Map<String, Object> getQ22Value() {
        return _2options;
    }

    public Map<String, Object> getQ23Value() {
        return _2options;
    }

    public Map<String, Object> getQ24Value() {
        return _5options;
    }

    public Map<String, Object> getQ25Value() {
        return _5options;
    }

    public Map<String, Object> getQ26Value() {
        return _5options;
    }

    public Map<String, Object> getQ27Value() {
        return _5options;
    }

    public String getCom_TeachingApproachesValue() {
        return com_TeachingApproaches;
    }

    public String getComfeedbackAsemenstsValue() {
        return comfeedbackAsemensts;
    }

    public String getComRecourseAdminstrationValue() {
        return comRecourseAdminstration;
    }

    public String getComAdditionalQuestionsValue() {
        return comAdditionalQuestions;
    }

    public String getComOverallExpValue() {
        return comOverallExp;
    }

    public String getComStdSelfEvaluationValue() {
        return comStdSelfEvaluation;
    }

    public String getchangesRecomendingValue() {
        return changesRecomending;
    }

    public String getLikeBestAboutInstructorValue() {
        return likeBestAboutInstructor;
    }

    public String getLikeLeastAboutInstructorValue() {
        return likeLeastAboutInstructor;
    }

    public String getFurtherConstructiveComValue() {
        return furtherConstructiveCom;
    }

    @Override
    public String toString() {
        return this.q1 + "" + this.q2 + "" + this.q3 + "" + this.q4 + "" + this.q5 + "" + this.q6 + "" + this.q7 + "" + this.q8 + "" + this.q9 + "" + this.q10 + "" + this.q11 + "" + this.q12 + "" + this.q13 + "" + this.q15 + "" + this.q16 + "" + this.q17 + "" + this.q18 + "" + this.q20 + "" + this.q21 + "" + this.q22 + "" + this.q23 + "" + this.q24 + "" + this.q25 + "" + this.q26 + "" + this.q27 + "" + this.com_TeachingApproaches + "" + this.comfeedbackAsemensts + "" + this.comRecourseAdminstration + "" + this.comAdditionalQuestions + "" + this.comOverallExp + "" + this.comStdSelfEvaluation + "" + this.changesRecomending + "" + this.likeBestAboutInstructor + "" + this.likeLeastAboutInstructor + "" + this.furtherConstructiveCom;
    }

}
