package FileShareApp;

/**
* FileShareApp/fileshareHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fileshare.idl
* Tuesday, May 24, 2022 9:18:48 PM PKT
*/

public final class fileshareHolder implements org.omg.CORBA.portable.Streamable
{
  public FileShareApp.fileshare value = null;

  public fileshareHolder ()
  {
  }

  public fileshareHolder (FileShareApp.fileshare initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileShareApp.fileshareHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileShareApp.fileshareHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileShareApp.fileshareHelper.type ();
  }

}
